### ISSUE TITLE
Choosing the image(s) for prediction 

### ISSUE THREAD

**Issue by Phoenix-313** [luisquintanilla/DeppLearning_ImageClassification_API#2]
Hi Luis,

I hope all is well. 

Sorry for posting this here, but I did post it in dotnet/machinelearning-samples repo as you asked a few days ago but I got no answer which I need urgently. 

I was able to save the trained model and load it for new predictions, but I'm trying to choose specific images to run the model on instead of creating a test data as the tutorial shows but no luck unfortunately. 

Could you please help? 

Many thanks for the great tutorials and support!

**Comment by luisquintanilla** [comment]
Hi @Phoenix-313 I've replied to your issue in machinelearning-samples. Hope that helps.

**Comment by luisquintanilla** [comment]
Here's the issue for reference https://github.com/dotnet/machinelearning-samples/issues/793
